// SQL Quest Levels Curriculum (Levels 1 to 50)
const LEVELS = [
  // --- WORLD 1: ABSOLUTE BEGINNER (1-10) ---
  {
    id: 1,
    world: 1,
    title: "What is SQL?",
    concept: "A database is an organized collection of data. In relational databases, data is stored in **Tables** made of **Columns** (fields) and **Rows** (records). SQL (Structured Query Language) is the standard language used to communicate with databases.",
    syntax: "-- Identify the structures in the database\n-- No query writing required for this level, just choose the correct definition!",
    example: "Table: employees\nColumns: id, name, salary\nRow: 1 | Steven King | 150000",
    database: "company",
    tables: ["employees"],
    challenge: "Look at the EMPLOYEES schema below. Select the query that correctly queries all columns from the employees table. (Hint: In SQL, the asterisk * represents 'all columns').",
    hint: "The basic structure is: SELECT * FROM table_name;",
    solution: "SELECT * FROM employees",
    requiredKeywords: ["select", "*", "from", "employees"],
    interactiveType: "multiple-choice",
    options: [
      "SELECT ALL FROM employees",
      "SELECT * FROM employees",
      "GET employees",
      "SELECT employees"
    ]
  },
  {
    id: 2,
    world: 1,
    title: "SELECT *",
    concept: "To retrieve data from a database, we use the `SELECT` statement. The asterisk (`*`) is a wildcard character that tells the database to return **all columns** from the specified table.",
    syntax: "SELECT * FROM table_name;",
    example: "SELECT * FROM departments;",
    database: "company",
    tables: ["departments"],
    challenge: "Write a query to retrieve all columns and all rows from the departments table.",
    hint: "Use SELECT followed by an asterisk, then FROM, followed by the table name: departments.",
    solution: "SELECT * FROM departments",
    requiredKeywords: ["select", "*", "from", "departments"]
  },
  {
    id: 3,
    world: 1,
    title: "Column Selection",
    concept: "Instead of retrieving all columns with `*`, you can select specific columns by listing their names separated by commas. This improves performance and keeps the results relevant.",
    syntax: "SELECT column1, column2 FROM table_name;",
    example: "SELECT name, email FROM employees;",
    database: "company",
    tables: ["employees"],
    challenge: "Select only the name and salary columns from the employees table.",
    hint: "List the column names name and salary (separated by a comma) right after the SELECT keyword.",
    solution: "SELECT name, salary FROM employees",
    requiredKeywords: ["select", "name", "salary", "from", "employees"]
  },
  {
    id: 4,
    world: 1,
    title: "DISTINCT",
    concept: "The `DISTINCT` keyword is used in the `SELECT` statement to retrieve only unique values. It removes all duplicate values from the output.",
    syntax: "SELECT DISTINCT column_name FROM table_name;",
    example: "SELECT DISTINCT job_id FROM employees;",
    database: "company",
    tables: ["employees"],
    challenge: "Find all unique department IDs in the employees table.",
    hint: "Put DISTINCT right before the column name department_id.",
    solution: "SELECT DISTINCT department_id FROM employees",
    requiredKeywords: ["select", "distinct", "department_id", "from", "employees"]
  },
  {
    id: 5,
    world: 1,
    title: "WHERE",
    concept: "The `WHERE` clause is used to filter records. It ensures that only rows meeting a specific condition are returned.",
    syntax: "SELECT column1, column2 FROM table_name WHERE condition;",
    example: "SELECT * FROM employees WHERE salary > 100000;",
    database: "company",
    tables: ["employees"],
    challenge: "Retrieve all details of employees who earn a salary greater than 80000.",
    hint: "Your query should end with: WHERE salary > 80000",
    solution: "SELECT * FROM employees WHERE salary > 80000",
    requiredKeywords: ["select", "from", "employees", "where", "salary", ">"]
  },
  {
    id: 6,
    world: 1,
    title: "Comparison Operators",
    concept: "SQL supports standard comparison operators in the `WHERE` clause: `=` (equal), `!=` or `<>` (not equal), `>` (greater than), `<` (less than), `>=` (greater or equal), `<=` (less or equal).",
    syntax: "SELECT * FROM table WHERE column <> value;",
    example: "SELECT * FROM employees WHERE department_id = 90;",
    database: "company",
    tables: ["employees"],
    challenge: "Find all employees who do NOT work in department 90. Use the <> operator.",
    hint: "Write: WHERE department_id <> 90",
    solution: "SELECT * FROM employees WHERE department_id <> 90",
    requiredKeywords: ["select", "from", "employees", "where", "department_id", "<>"]
  },
  {
    id: 7,
    world: 1,
    title: "AND / OR",
    concept: "You can combine multiple filters in a `WHERE` clause using logical operators. `AND` returns rows where *all* conditions are true. `OR` returns rows where *at least one* condition is true.",
    syntax: "WHERE condition1 AND/OR condition2;",
    example: "SELECT * FROM employees WHERE department_id = 90 AND salary > 120000;",
    database: "company",
    tables: ["employees"],
    challenge: "Find employees who work in department 80 AND earn less than 70000.",
    hint: "Use: WHERE department_id = 80 AND salary < 70000",
    solution: "SELECT * FROM employees WHERE department_id = 80 AND salary < 70000",
    requiredKeywords: ["select", "from", "employees", "where", "department_id", "and", "salary", "<"]
  },
  {
    id: 8,
    world: 1,
    title: "NOT",
    concept: "The `NOT` operator displays a record if the condition(s) are NOT true.",
    syntax: "SELECT columns FROM table WHERE NOT condition;",
    example: "SELECT * FROM employees WHERE NOT department_id = 90;",
    database: "company",
    tables: ["employees"],
    challenge: "Select all employees who are NOT sales managers (job_id is NOT 'SA_MAN'). Use the NOT operator.",
    hint: "Format the filter as: WHERE NOT job_id = 'SA_MAN'",
    solution: "SELECT * FROM employees WHERE NOT job_id = 'SA_MAN'",
    requiredKeywords: ["select", "from", "employees", "where", "not", "job_id", "="]
  },
  {
    id: 9,
    world: 1,
    title: "BETWEEN",
    concept: "The `BETWEEN` operator selects values within a given range. The values can be numbers, text, or dates. Crucially, the start and end values are **inclusive**.",
    syntax: "WHERE column BETWEEN value1 AND value2;",
    example: "SELECT * FROM employees WHERE salary BETWEEN 50000 AND 90000;",
    database: "company",
    tables: ["employees"],
    challenge: "Find all employees with a salary between 60000 and 100000.",
    hint: "Write: WHERE salary BETWEEN 60000 AND 100000",
    solution: "SELECT * FROM employees WHERE salary BETWEEN 60000 AND 100000",
    requiredKeywords: ["select", "from", "employees", "where", "salary", "between", "and"]
  },
  {
    id: 10,
    world: 1,
    title: "IN",
    concept: "The `IN` operator allows you to specify multiple values in a `WHERE` clause. It acts as shorthand for multiple `OR` conditions.",
    syntax: "WHERE column IN (value1, value2, ...);",
    example: "SELECT * FROM employees WHERE department_id IN (10, 60, 90);",
    database: "company",
    tables: ["employees"],
    challenge: "Retrieve employees who belong to department 10 or 60 or 80. Use the IN operator.",
    hint: "Use: WHERE department_id IN (10, 60, 80)",
    solution: "SELECT * FROM employees WHERE department_id IN (10, 60, 80)",
    requiredKeywords: ["select", "from", "employees", "where", "department_id", "in"]
  },

  // --- WORLD 2: SQL FOUNDATION (11-20) ---
  {
    id: 11,
    world: 2,
    title: "LIKE",
    concept: "The `LIKE` operator is used to search for a specified pattern in a column. Wildcards used:\n- `%` represents zero, one, or multiple characters.\n- `_` represents a single character.",
    syntax: "WHERE column LIKE 'pattern';",
    example: "SELECT * FROM employees WHERE name LIKE 'A%'; -- Names starting with A",
    database: "company",
    tables: ["employees"],
    challenge: "Find all employees whose name contains the letters 'er'.",
    hint: "Use: WHERE name LIKE '%er%'",
    solution: "SELECT * FROM employees WHERE name LIKE '%er%'",
    requiredKeywords: ["select", "from", "employees", "where", "name", "like", "%er%"]
  },
  {
    id: 12,
    world: 2,
    title: "NULL",
    concept: "A field with a NULL value is a field with no value. You cannot test for NULL values with comparison operators (like `= NULL` or `!= NULL`). Instead, use `IS NULL` and `IS NOT NULL`.",
    syntax: "WHERE column IS NULL;\nWHERE column IS NOT NULL;",
    example: "SELECT * FROM employees WHERE manager_id IS NULL;",
    database: "company",
    tables: ["employees"],
    challenge: "Select all employees who do NOT have a manager (manager_id is null).",
    hint: "Use: WHERE manager_id IS NULL",
    solution: "SELECT * FROM employees WHERE manager_id IS NULL",
    requiredKeywords: ["select", "from", "employees", "where", "manager_id", "is", "null"]
  },
  {
    id: 13,
    world: 2,
    title: "ORDER BY",
    concept: "The `ORDER BY` keyword is used to sort the result-set in ascending (`ASC`) or descending (`DESC`) order. It sorts ascending by default.",
    syntax: "SELECT columns FROM table ORDER BY column1 [ASC|DESC];",
    example: "SELECT * FROM employees ORDER BY salary DESC;",
    database: "company",
    tables: ["employees"],
    challenge: "Retrieve all employees sorted by their hire date, starting from the most recent hire (descending).",
    hint: "Add ORDER BY hire_date DESC at the end of the query.",
    solution: "SELECT * FROM employees ORDER BY hire_date DESC",
    requiredKeywords: ["select", "from", "employees", "order", "by", "hire_date", "desc"]
  },
  {
    id: 14,
    world: 2,
    title: "FETCH / Limiting Results",
    concept: "In standard Oracle SQL, to limit the number of rows returned, we use the `FETCH FIRST n ROWS ONLY` clause. This is modern, SQL:2008 standard syntax compatible with Oracle 12c+.",
    syntax: "SELECT columns FROM table ORDER BY column FETCH FIRST n ROWS ONLY;",
    example: "SELECT name FROM employees ORDER BY salary DESC FETCH FIRST 3 ROWS ONLY;",
    database: "company",
    tables: ["employees"],
    challenge: "Select the name and salary of the top 3 highest-paid employees in the company.",
    hint: "Sort the employees by salary in descending order, then apply: FETCH FIRST 3 ROWS ONLY",
    solution: "SELECT name, salary FROM employees ORDER BY salary DESC FETCH FIRST 3 ROWS ONLY",
    requiredKeywords: ["select", "from", "employees", "order", "by", "salary", "desc", "fetch", "first", "3", "rows", "only"]
  },
  {
    id: 15,
    world: 2,
    title: "Aggregate Functions",
    concept: "Aggregate functions perform calculations on multiple values and return a single value: `COUNT()`, `SUM()`, `AVG()`, `MIN()`, and `MAX()`.",
    syntax: "SELECT AVG(salary), MAX(salary) FROM employees;",
    example: "SELECT COUNT(*), SUM(salary) FROM employees;",
    database: "company",
    tables: ["employees"],
    challenge: "Find the total headcount (using COUNT), the average salary (using AVG), and the maximum salary (using MAX) of all employees.",
    hint: "Your select list should be: COUNT(*), AVG(salary), MAX(salary)",
    solution: "SELECT COUNT(*), AVG(salary), MAX(salary) FROM employees",
    requiredKeywords: ["select", "count(*)", "avg(salary)", "max(salary)", "from", "employees"]
  },
  {
    id: 16,
    world: 2,
    title: "GROUP BY",
    concept: "The `GROUP BY` statement groups rows that have the same values into summary rows. It is often used with aggregate functions to calculate stats per group.",
    syntax: "SELECT column, AGG_FUNC(column2) FROM table GROUP BY column;",
    example: "SELECT department_id, AVG(salary) FROM employees GROUP BY department_id;",
    database: "company",
    tables: ["employees"],
    challenge: "Find the number of employees (COUNT) and the average salary in each department. Group by department_id.",
    hint: "SELECT department_id, COUNT(*), AVG(salary) FROM employees GROUP BY department_id",
    solution: "SELECT department_id, COUNT(*), AVG(salary) FROM employees GROUP BY department_id",
    requiredKeywords: ["select", "department_id", "count(*)", "avg(salary)", "from", "employees", "group", "by"]
  },
  {
    id: 17,
    world: 2,
    title: "HAVING",
    concept: "The `HAVING` clause was added to SQL because the `WHERE` keyword cannot be used with aggregate functions. `WHERE` filters rows *before* grouping, while `HAVING` filters groups *after* aggregation.",
    syntax: "SELECT column, AGG(col) FROM table GROUP BY column HAVING AGG(col) > value;",
    example: "SELECT department_id, COUNT(*) FROM employees GROUP BY department_id HAVING COUNT(*) > 5;",
    database: "company",
    tables: ["employees"],
    challenge: "Find the department IDs and their average salary, but only include departments where the average salary is greater than 70000.",
    hint: "Use GROUP BY department_id HAVING AVG(salary) > 70000",
    solution: "SELECT department_id, AVG(salary) FROM employees GROUP BY department_id HAVING AVG(salary) > 70000",
    requiredKeywords: ["select", "department_id", "avg(salary)", "from", "employees", "group", "by", "having", "70000"]
  },
  {
    id: 18,
    world: 2,
    title: "String Functions",
    concept: "SQL provides functions to manipulate text strings. Common Oracle functions include:\n- `UPPER(str)` / `LOWER(str)`\n- `LENGTH(str)` - character count\n- `SUBSTR(str, pos, len)` - substring extraction\n- `TRIM(str)` - removes whitespace.",
    syntax: "SELECT UPPER(name), SUBSTR(email, 1, 5) FROM employees;",
    example: "SELECT LOWER(name) FROM employees;",
    database: "company",
    tables: ["employees"],
    challenge: "Retrieve the employee names in UPPERCASE and the character count of their emails as 'email_len'.",
    hint: "Use: SELECT UPPER(name), LENGTH(email) AS email_len FROM employees",
    solution: "SELECT UPPER(name), LENGTH(email) AS email_len FROM employees",
    requiredKeywords: ["select", "upper(name)", "length(email)", "as", "email_len", "from", "employees"]
  },
  {
    id: 19,
    world: 2,
    title: "Numeric Functions",
    concept: "Numeric functions handle mathematical transformations:\n- `ROUND(num, dec)` - rounds to decimal places\n- `TRUNC(num, dec)` - truncates values\n- `MOD(num, div)` - modulo (remainder)\n- `ABS(num)` - absolute value\n- `CEIL(num)` / `FLOOR(num)` - ceiling / floor rounding.",
    syntax: "SELECT ROUND(salary/12, 2) FROM employees;",
    example: "SELECT MOD(id, 2) FROM employees;",
    database: "company",
    tables: ["employees"],
    challenge: "Calculate the monthly salary for each employee by dividing their annual salary by 12. Round the result to 2 decimal places.",
    hint: "Use ROUND(salary / 12, 2) in your SELECT list.",
    solution: "SELECT name, ROUND(salary / 12, 2) AS monthly_salary FROM employees",
    requiredKeywords: ["select", "round(salary", "12", "2)", "from", "employees"]
  },
  {
    id: 20,
    world: 2,
    title: "Date Functions",
    concept: "Date handling is crucial. In Oracle SQL, `SYSDATE` returns the current system date. Important functions:\n- `ADD_MONTHS(date, n)`: Adds months.\n- `MONTHS_BETWEEN(date1, date2)`: Months difference.\n- `LAST_DAY(date)`: Last day of the date's month.",
    syntax: "SELECT ADD_MONTHS(SYSDATE, 6) FROM dual;",
    example: "SELECT MONTHS_BETWEEN(SYSDATE, hire_date) FROM employees;",
    database: "company",
    tables: ["employees"],
    challenge: "Calculate how many months each employee has been with the company. Use '2025-01-01' as the reference end date.",
    hint: "Use MONTHS_BETWEEN('2025-01-01', hire_date) or cast dates appropriately. In this environment, you can use the literal string date in the function.",
    solution: "SELECT name, MONTHS_BETWEEN('2025-01-01', hire_date) AS months_worked FROM employees",
    requiredKeywords: ["select", "months_between(", "hire_date", "from", "employees"]
  },

  // --- WORLD 3: INTERMEDIATE SQL (21-30) ---
  {
    id: 21,
    world: 3,
    title: "CASE",
    concept: "The `CASE` statement goes through conditions and returns a value when the first condition is met (like an IF-THEN-ELSE statement). Once a condition is true, it stops reading and returns the result.",
    syntax: "CASE WHEN condition THEN val1 WHEN condition2 THEN val2 ELSE val3 END",
    example: "SELECT name, CASE WHEN salary > 100000 THEN 'Rich' ELSE 'Regular' END AS status FROM employees;",
    database: "company",
    tables: ["employees"],
    challenge: "Show employee names, salaries, and a custom column 'salary_tier'. If salary > 100000, Tier is 'Tier 1'; if salary > 50000, it's 'Tier 2'; otherwise 'Tier 3'.",
    hint: "Write: CASE WHEN salary > 100000 THEN 'Tier 1' WHEN salary > 50000 THEN 'Tier 2' ELSE 'Tier 3' END AS salary_tier",
    solution: "SELECT name, salary, CASE WHEN salary > 100000 THEN 'Tier 1' WHEN salary > 50000 THEN 'Tier 2' ELSE 'Tier 3' END AS salary_tier FROM employees",
    requiredKeywords: ["select", "case", "when", "then", "else", "end", "as", "salary_tier", "from", "employees"]
  },
  {
    id: 22,
    world: 3,
    title: "Aliases",
    concept: "Aliases are used to give a table or a column in a table a temporary name. Column aliases are created with the `AS` keyword. Table aliases are written immediately after the table name.",
    syntax: "SELECT column_name AS alias_name FROM table_name t;",
    example: "SELECT e.name FROM employees e;",
    database: "company",
    tables: ["employees"],
    challenge: "Rename the column name to 'employee_name' and display it from the employees table aliased as 'emp'.",
    hint: "Write: SELECT emp.name AS employee_name FROM employees emp",
    solution: "SELECT emp.name AS employee_name FROM employees emp",
    requiredKeywords: ["select", "as", "employee_name", "from", "employees", "emp"]
  },
  {
    id: 23,
    world: 3,
    title: "INNER JOIN",
    concept: "An `INNER JOIN` selects records that have matching values in both tables. You must specify the condition on which to link the tables using the `ON` clause.",
    syntax: "SELECT t1.col, t2.col FROM table1 t1 INNER JOIN table2 t2 ON t1.key = t2.key;",
    example: "SELECT e.name, d.department_name FROM employees e INNER JOIN departments d ON e.department_id = d.department_id;",
    database: "company",
    tables: ["employees", "departments"],
    challenge: "Retrieve the employee name and their department name. Join the employees and departments tables.",
    hint: "Use INNER JOIN on department_id.",
    solution: "SELECT e.name, d.department_name FROM employees e INNER JOIN departments d ON e.department_id = d.department_id",
    requiredKeywords: ["select", "inner", "join", "on", "employees", "departments", "department_id"]
  },
  {
    id: 24,
    world: 3,
    title: "LEFT JOIN",
    concept: "The `LEFT JOIN` (or `LEFT OUTER JOIN`) returns all records from the left table, and the matched records from the right table. If there is no match, the result is NULL from the right side.",
    syntax: "SELECT columns FROM table1 LEFT JOIN table2 ON table1.key = table2.key;",
    example: "SELECT e.name, d.department_name FROM employees e LEFT JOIN departments d ON e.department_id = d.department_id;",
    database: "company",
    tables: ["employees", "departments"],
    challenge: "List all departments and the names of employees in them, showing departments even if they have no employees. (Departments is left, employees is right).",
    hint: "Write: FROM departments d LEFT JOIN employees e ON d.department_id = e.department_id",
    solution: "SELECT d.department_name, e.name FROM departments d LEFT JOIN employees e ON d.department_id = e.department_id",
    requiredKeywords: ["select", "left", "join", "on", "departments", "employees", "department_id"]
  },
  {
    id: 25,
    world: 3,
    title: "RIGHT JOIN",
    concept: "The `RIGHT JOIN` (or `RIGHT OUTER JOIN`) returns all records from the right table, and the matched records from the left table. If there is no match, the result is NULL from the left side.",
    syntax: "SELECT columns FROM table1 RIGHT JOIN table2 ON table1.key = table2.key;",
    example: "SELECT e.name, d.department_name FROM employees e RIGHT JOIN departments d ON e.department_id = d.department_id;",
    database: "company",
    tables: ["employees", "departments"],
    challenge: "Join employees (left) and departments (right) using a RIGHT JOIN to retrieve employee name and department name, keeping departments with no employees.",
    hint: "Write: FROM employees e RIGHT JOIN departments d ON e.department_id = d.department_id",
    solution: "SELECT e.name, d.department_name FROM employees e RIGHT JOIN departments d ON e.department_id = d.department_id",
    requiredKeywords: ["select", "right", "join", "on", "employees", "departments", "department_id"]
  },
  {
    id: 26,
    world: 3,
    title: "FULL OUTER JOIN",
    concept: "The `FULL OUTER JOIN` returns all records when there is a match in left or right table records. It combines the effects of both LEFT and RIGHT joins.",
    syntax: "SELECT columns FROM table1 FULL OUTER JOIN table2 ON table1.key = table2.key;",
    database: "company",
    tables: ["employees", "departments"],
    challenge: "Perform a FULL OUTER JOIN between employees and departments to list employee name and department name. This will show all employees and all departments.",
    hint: "Write: FROM employees e FULL OUTER JOIN departments d ON e.department_id = d.department_id",
    solution: "SELECT e.name, d.department_name FROM employees e FULL OUTER JOIN departments d ON e.department_id = d.department_id",
    requiredKeywords: ["select", "full", "outer", "join", "on", "employees", "departments", "department_id"]
  },
  {
    id: 27,
    world: 3,
    title: "SELF JOIN",
    concept: "A self join is a regular join, but the table is joined with itself. This is incredibly useful for querying hierarchical relationships within a single table, like employee-manager data.",
    syntax: "SELECT a.col, b.col FROM table a, table b WHERE a.key = b.key;",
    example: "SELECT e.name AS employee, m.name AS manager FROM employees e INNER JOIN employees m ON e.manager_id = m.id;",
    database: "company",
    tables: ["employees"],
    challenge: "Retrieve employee name and their manager's name from the employees table. Alias the manager table as 'm' and employee table as 'e'.",
    hint: "Use: INNER JOIN employees m ON e.manager_id = m.id",
    solution: "SELECT e.name AS employee, m.name AS manager FROM employees e INNER JOIN employees m ON e.manager_id = m.id",
    requiredKeywords: ["select", "join", "employees", "manager_id"]
  },
  {
    id: 28,
    world: 3,
    title: "Multiple Table JOINs",
    concept: "You can join three or more tables by chaining `JOIN` clauses. SQL processes them sequentially from left to right.",
    syntax: "SELECT * FROM t1 JOIN t2 ON t1.id = t2.id JOIN t3 ON t2.key = t3.key;",
    database: "company",
    tables: ["employees", "departments", "locations"],
    challenge: "Retrieve employee name, their department name, and the city where their department is located.",
    hint: "Join employees to departments on department_id, and then join departments to locations on location_id.",
    solution: "SELECT e.name, d.department_name, l.city FROM employees e INNER JOIN departments d ON e.department_id = d.department_id INNER JOIN locations l ON d.location_id = l.location_id",
    requiredKeywords: ["select", "join", "departments", "locations", "department_id", "location_id"]
  },
  {
    id: 29,
    world: 3,
    title: "Subqueries",
    concept: "A Subquery or Inner Query is a query nested inside another SQL query (Outer Query). Subqueries in the `WHERE` clause are evaluated first, and their results are passed to the outer query filter.",
    syntax: "SELECT * FROM t WHERE col > (SELECT AVG(col) FROM t);",
    database: "company",
    tables: ["employees"],
    challenge: "Select all employees who earn MORE than the average salary of the entire company.",
    hint: "Write: WHERE salary > (SELECT AVG(salary) FROM employees)",
    solution: "SELECT name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees)",
    requiredKeywords: ["select", "from", "employees", "where", "salary", ">", "avg(salary)"]
  },
  {
    id: 30,
    world: 3,
    title: "Correlated Subqueries",
    concept: "A correlated subquery is a subquery that uses values from the outer query. It is evaluated once for each row processed by the outer query.",
    syntax: "SELECT * FROM t o WHERE col > (SELECT AVG(col) FROM t i WHERE i.grp = o.grp);",
    database: "company",
    tables: ["employees"],
    challenge: "Find employees who earn more than the average salary of their specific department.",
    hint: "Use an outer alias e.g., 'e_out'. The inner query will look like: SELECT AVG(e_in.salary) FROM employees e_in WHERE e_in.department_id = e_out.department_id",
    solution: "SELECT e_out.name, e_out.salary FROM employees e_out WHERE e_out.salary > (SELECT AVG(e_in.salary) FROM employees e_in WHERE e_in.department_id = e_out.department_id)",
    requiredKeywords: ["select", "from", "employees", "where", "salary", ">", "avg(salary)", "department_id", "="]
  },

  // --- WORLD 4: ADVANCED SQL (31-40) ---
  {
    id: 31,
    world: 4,
    title: "EXISTS / NOT EXISTS",
    concept: "The `EXISTS` operator is used to test for the existence of any record in a subquery. If the subquery returns one or more rows, `EXISTS` is TRUE.",
    syntax: "SELECT cols FROM t WHERE EXISTS (SELECT 1 FROM t2 WHERE t.key = t2.key);",
    database: "ecommerce",
    tables: ["customers", "orders"],
    challenge: "Retrieve the names (first_name, last_name) of customers who have placed at least one order. Use the EXISTS operator.",
    hint: "Subquery: SELECT 1 FROM orders o WHERE o.customer_id = c.customer_id",
    solution: "SELECT c.first_name, c.last_name FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.customer_id)",
    requiredKeywords: ["select", "from", "customers", "where", "exists", "orders", "customer_id"]
  },
  {
    id: 32,
    world: 4,
    title: "ANY / ALL",
    concept: "The `ANY` and `ALL` operators allow you to perform a comparison between a single column value and a range of values returned by a subquery.",
    syntax: "WHERE column > ANY (SELECT col FROM t);\nWHERE column > ALL (SELECT col FROM t);",
    database: "company",
    tables: ["employees"],
    challenge: "Find employees who earn more than ALL employees in department 60 (i.e. more than the maximum salary of department 60). Use the ALL operator.",
    hint: "Write: WHERE salary > ALL (SELECT salary FROM employees WHERE department_id = 60)",
    solution: "SELECT name, salary FROM employees WHERE salary > ALL (SELECT salary FROM employees WHERE department_id = 60)",
    requiredKeywords: ["select", "from", "employees", "where", "salary", ">", "all", "department_id", "60"]
  },
  {
    id: 33,
    world: 4,
    title: "UNION",
    concept: "The `UNION` operator is used to combine the result-set of two or more `SELECT` statements. `UNION` removes duplicate rows between the sets.",
    syntax: "SELECT col FROM t1 UNION SELECT col FROM t2;",
    database: "company",
    tables: ["employees", "departments"],
    challenge: "Get a list of all IDs that represent either an employee manager ID or a department manager ID. Combine them using UNION.",
    hint: "SELECT manager_id FROM employees UNION SELECT manager_id FROM departments",
    solution: "SELECT manager_id FROM employees UNION SELECT manager_id FROM departments",
    requiredKeywords: ["select", "manager_id", "from", "union", "employees", "departments"]
  },
  {
    id: 34,
    world: 4,
    title: "UNION ALL",
    concept: "The `UNION ALL` operator combines the result-set of two or more `SELECT` statements, but unlike `UNION`, it **retains duplicate rows** and is faster.",
    syntax: "SELECT col FROM t1 UNION ALL SELECT col FROM t2;",
    database: "company",
    tables: ["employees", "departments"],
    challenge: "Get a list of all manager IDs from both employees and departments, retaining duplicates using UNION ALL.",
    hint: "Replace the UNION keyword with UNION ALL.",
    solution: "SELECT manager_id FROM employees UNION ALL SELECT manager_id FROM departments",
    requiredKeywords: ["select", "manager_id", "from", "union", "all", "employees", "departments"]
  },
  {
    id: 35,
    world: 4,
    title: "INTERSECT",
    concept: "The `INTERSECT` operator returns only the rows that are returned by **both** SELECT queries.",
    syntax: "SELECT col FROM t1 INTERSECT SELECT col FROM t2;",
    database: "company",
    tables: ["employees", "departments"],
    challenge: "Find the manager IDs that are active in both the employees table and the departments table using INTERSECT.",
    hint: "Write: SELECT manager_id FROM employees INTERSECT SELECT manager_id FROM departments",
    solution: "SELECT manager_id FROM employees INTERSECT SELECT manager_id FROM departments",
    requiredKeywords: ["select", "manager_id", "from", "intersect", "employees", "departments"]
  },
  {
    id: 36,
    world: 4,
    title: "MINUS",
    concept: "The `MINUS` operator (called `EXCEPT` in some databases, but `MINUS` in Oracle SQL) returns rows from the first query that are not returned by the second query.",
    syntax: "SELECT col FROM t1 MINUS SELECT col FROM t2;",
    database: "company",
    tables: ["employees", "departments"],
    challenge: "Find the employee IDs that are NOT manager IDs in departments. (Subtract department manager IDs from employee IDs using MINUS).",
    hint: "Write: SELECT id FROM employees MINUS SELECT manager_id FROM departments",
    solution: "SELECT id FROM employees MINUS SELECT manager_id FROM departments",
    requiredKeywords: ["select", "id", "manager_id", "from", "minus", "employees", "departments"]
  },
  {
    id: 37,
    world: 4,
    title: "Common Table Expressions (CTEs)",
    concept: "A Common Table Expression (`CTE`) is a temporary named result set that you can reference within a `SELECT`, `INSERT`, `UPDATE`, or `DELETE` statement. It is defined using the `WITH` keyword.",
    syntax: "WITH cte_name AS (SELECT ... ) SELECT * FROM cte_name;",
    example: "WITH high_pay AS (SELECT * FROM employees WHERE salary > 100000) SELECT name FROM high_pay;",
    database: "company",
    tables: ["employees"],
    challenge: "Define a CTE called 'dept_summary' that lists department_id and their average salary. Then query this CTE to find departments with an average salary above 80000.",
    hint: "WITH dept_summary AS (SELECT department_id, AVG(salary) AS avg_sal FROM employees GROUP BY department_id) SELECT department_id FROM dept_summary WHERE avg_sal > 80000",
    solution: "WITH dept_summary AS (SELECT department_id, AVG(salary) AS avg_sal FROM employees GROUP BY department_id) SELECT department_id FROM dept_summary WHERE avg_sal > 80000",
    requiredKeywords: ["with", "dept_summary", "as", "select", "department_id", "avg(salary)", "from", "group", "by", "where", "avg_sal", ">", "80000"]
  },
  {
    id: 38,
    world: 4,
    title: "Hierarchical Queries",
    concept: "Oracle SQL supports hierarchical queries to process tree-structured tables. We use `START WITH` to define the root node, and `CONNECT BY PRIOR` to define the parent-child relation.",
    syntax: "SELECT columns FROM table START WITH condition CONNECT BY PRIOR child_col = parent_col;",
    example: "SELECT name FROM employees START WITH manager_id IS NULL CONNECT BY PRIOR id = manager_id;",
    database: "company",
    tables: ["employees"],
    challenge: "Write a hierarchical query starting with the President (manager_id IS NULL) and connecting employees to their managers.",
    hint: "Write: START WITH manager_id IS NULL CONNECT BY PRIOR id = manager_id",
    solution: "SELECT name, job_id, manager_id FROM employees START WITH manager_id IS NULL CONNECT BY PRIOR id = manager_id",
    requiredKeywords: ["select", "from", "employees", "start", "with", "manager_id", "is", "null", "connect", "by", "prior", "id", "=", "manager_id"]
  },
  {
    id: 39,
    world: 4,
    title: "Analytic Functions",
    concept: "Analytic functions calculate an aggregate value based on a group of rows, but return a single row for each row of the query. Examples: `ROW_NUMBER()`, `RANK()`, and `DENSE_RANK()`.",
    syntax: "SELECT col, ROW_NUMBER() OVER (ORDER BY col DESC) FROM t;",
    database: "company",
    tables: ["employees"],
    challenge: "Assign a unique row number (name it 'row_num') and a dense rank (name it 'sal_rank') to all employees based on their salary in descending order.",
    hint: "Use ROW_NUMBER() OVER (ORDER BY salary DESC) AS row_num, and DENSE_RANK() OVER (ORDER BY salary DESC) AS sal_rank.",
    solution: "SELECT name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) AS row_num, DENSE_RANK() OVER (ORDER BY salary DESC) AS sal_rank FROM employees",
    requiredKeywords: ["select", "row_number()", "over", "order", "by", "salary", "desc", "dense_rank()", "as", "row_num", "sal_rank", "from", "employees"]
  },
  {
    id: 40,
    world: 4,
    title: "PARTITION BY",
    concept: "The `PARTITION BY` clause is used within analytic functions to partition the rows of the table. The function is evaluated separately for each partition.",
    syntax: "ROW_NUMBER() OVER (PARTITION BY group_col ORDER BY sort_col DESC)",
    database: "company",
    tables: ["employees"],
    challenge: "Rank employees within their department based on salary in descending order. Use DENSE_RANK() and name the column 'dept_rank'.",
    hint: "Use DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS dept_rank.",
    solution: "SELECT name, department_id, salary, DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS dept_rank FROM employees",
    requiredKeywords: ["select", "dense_rank()", "over", "partition", "by", "department_id", "order", "by", "salary", "desc", "as", "dept_rank", "from", "employees"]
  },

  // --- WORLD 5: SQL MASTER (41-50) ---
  {
    id: 41,
    world: 5,
    title: "Advanced Window Functions",
    concept: "Oracle window functions like `LAG` and `LEAD` allow you to query data from a preceding (LAG) or following (LEAD) row without performing a self-join.",
    syntax: "LAG(col, offset) OVER (ORDER BY col)\nLEAD(col, offset) OVER (ORDER BY col)",
    database: "company",
    tables: ["employees"],
    challenge: "For each employee, retrieve their salary and the salary of the employee who earns the next lower salary (the previous row when sorted by salary ascending). Name this column 'prev_salary'.",
    hint: "Use LAG(salary, 1) OVER (ORDER BY salary ASC) AS prev_salary.",
    solution: "SELECT name, salary, LAG(salary, 1) OVER (ORDER BY salary ASC) AS prev_salary FROM employees",
    requiredKeywords: ["select", "lag(salary,", "over", "order", "by", "salary", "asc", "as", "prev_salary", "from", "employees"]
  },
  {
    id: 42,
    world: 5,
    title: "Running Totals",
    concept: "We can compute running totals by applying `SUM` with a window clause `OVER (ORDER BY ...)` which implicitly aggregates rows from the beginning of the partition up to the current row.",
    syntax: "SUM(col) OVER (ORDER BY sort_col ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)",
    database: "company",
    tables: ["employees"],
    challenge: "Calculate the running total of salaries (cumulative sum) as employees are hired (ordered by hire_date). Name the running total column 'running_total'.",
    hint: "Use: SUM(salary) OVER (ORDER BY hire_date) AS running_total",
    solution: "SELECT hire_date, name, salary, SUM(salary) OVER (ORDER BY hire_date) AS running_total FROM employees",
    requiredKeywords: ["select", "sum(salary)", "over", "order", "by", "hire_date", "as", "running_total", "from", "employees"]
  },
  {
    id: 43,
    world: 5,
    title: "Advanced Date & Time Queries",
    concept: "Real world analysis requires computing date boundary metrics. In Oracle, we can group data by month, query specific date offsets, or find date differentials using date math.",
    syntax: "SELECT TO_CHAR(hire_date, 'YYYY-MM') FROM employees;",
    database: "company",
    tables: ["employees"],
    challenge: "List the names of employees hired in the year 2021. Use hire_date details.",
    hint: "You can use: WHERE hire_date BETWEEN '2021-01-01' AND '2021-12-31' or use a substring/TO_CHAR method.",
    solution: "SELECT name, hire_date FROM employees WHERE hire_date BETWEEN '2021-01-01' AND '2021-12-31'",
    requiredKeywords: ["select", "hire_date", "from", "employees", "where", "between", "2021-01-01", "2021-12-31"]
  },
  {
    id: 44,
    world: 5,
    title: "Complex Subqueries",
    concept: "Complex reporting combines CTEs, subqueries, grouping, and cases to create detailed analytics in a single SQL query statement.",
    syntax: "SELECT * FROM (SELECT grp, MAX(val) FROM t GROUP BY grp);",
    database: "company",
    tables: ["employees"],
    challenge: "Find the employees who earn the highest salary in their respective departments.",
    hint: "Use a subquery in the WHERE clause: WHERE (department_id, salary) IN (SELECT department_id, MAX(salary) FROM employees GROUP BY department_id)",
    solution: "SELECT name, department_id, salary FROM employees WHERE (department_id, salary) IN (SELECT department_id, MAX(salary) FROM employees GROUP BY department_id)",
    requiredKeywords: ["select", "from", "employees", "where", "department_id", "salary", "in", "max(salary)", "group", "by"]
  },
  {
    id: 45,
    world: 5,
    title: "Complex JOIN Challenges",
    concept: "Querying raw operational databases requires joining 3 to 5 tables to map transactional structures (e.g. Orders, Order Items, Customers, and Products).",
    syntax: "SELECT c.name, p.name FROM customers c JOIN orders o ON ... JOIN order_items oi ON ... JOIN products p ON ...",
    database: "ecommerce",
    tables: ["customers", "orders", "order_items", "products"],
    challenge: "Retrieve customer first_name, order_id, product_name, and the item price. Join customers, orders, order_items, and products.",
    hint: "Chain three joins: customers to orders on customer_id, orders to order_items on order_id, and order_items to products on product_id.",
    solution: "SELECT c.first_name, o.order_id, p.product_name, oi.price FROM customers c INNER JOIN orders o ON c.customer_id = o.customer_id INNER JOIN order_items oi ON o.order_id = oi.order_id INNER JOIN products p ON oi.product_id = p.product_id",
    requiredKeywords: ["select", "inner", "join", "on", "customers", "orders", "order_items", "products"]
  },
  {
    id: 46,
    world: 5,
    title: "Data Modification",
    concept: "DML (Data Manipulation Language) statements are: `INSERT` (add records), `UPDATE` (modify records), and `DELETE` (remove records). Safely filter updates and deletes with `WHERE`.",
    syntax: "INSERT INTO table (cols) VALUES (vals);\nUPDATE table SET col = val WHERE condition;\nDELETE FROM table WHERE condition;",
    database: "ecommerce",
    tables: ["products"],
    challenge: "Write an UPDATE statement to increase the price of all products in the 'Audio' category by 20.",
    hint: "UPDATE products SET price = price + 20 WHERE category = 'Audio'",
    solution: "UPDATE products SET price = price + 20 WHERE category = 'Audio'",
    requiredKeywords: ["update", "products", "set", "price", "=", "where", "category", "'Audio'"]
  },
  {
    id: 47,
    world: 5,
    title: "MERGE",
    concept: "The Oracle `MERGE` statement (UPSERT) selects rows from one or more sources and updates or inserts them into a target table, depending on whether a matching condition is met.",
    syntax: "MERGE INTO target USING source ON (condition) WHEN MATCHED THEN UPDATE SET ... WHEN NOT MATCHED THEN INSERT ...",
    database: "ecommerce",
    tables: ["products"],
    challenge: "Look at the MERGE syntax description. In Oracle SQL, which keyword specifies the table you want to insert or update data INTO?",
    hint: "Look at the syntax: MERGE INTO target_table",
    solution: "INTO",
    requiredKeywords: ["into"],
    interactiveType: "multiple-choice",
    options: [
      "USING",
      "INTO",
      "MATCHED",
      "UPDATE"
    ]
  },
  {
    id: 48,
    world: 5,
    title: "Views & Database Objects",
    concept: "A View is a virtual table based on the result-set of an SQL statement. `CREATE VIEW view_name AS ...` generates this virtual wrapper. Other DB objects include Sequences (auto-number generators) and Indexes (speed up retrieval).",
    syntax: "CREATE VIEW view_name AS SELECT ...",
    database: "company",
    tables: ["employees"],
    challenge: "Create a view named 'high_salary_emp' that contains all details of employees earning more than 80000.",
    hint: "Use: CREATE VIEW high_salary_emp AS SELECT * FROM employees WHERE salary > 80000",
    solution: "CREATE VIEW high_salary_emp AS SELECT * FROM employees WHERE salary > 80000",
    requiredKeywords: ["create", "view", "high_salary_emp", "as", "select", "from", "employees", "where", "salary", ">", "80000"]
  },
  {
    id: 49,
    world: 5,
    title: "Real-World SQL Challenges",
    concept: "Professional developers write complex reporting queries combining aggregates, joins, filters, and subqueries. This prepares you for APEX dashboard statistics.",
    syntax: "Complex multi-table queries.",
    database: "ecommerce",
    tables: ["customers", "orders"],
    challenge: "Find the customer_id, first_name, and last_name of customers who have NEVER placed any order.",
    hint: "Use a LEFT JOIN between customers and orders, filtering WHERE o.order_id IS NULL, or use NOT IN/NOT EXISTS.",
    solution: "SELECT c.customer_id, c.first_name, c.last_name FROM customers c LEFT JOIN orders o ON c.customer_id = o.customer_id WHERE o.order_id IS NULL",
    requiredKeywords: ["select", "from", "customers", "left", "join", "orders", "on", "where", "is", "null"]
  },
  {
    id: 50,
    world: 5,
    title: "SQL MASTER EXAM 🏆",
    concept: "Congratulations on reaching the final Level! The SQL Master Exam evaluates your understanding of all key concepts. Solve the final challenges to claim your certificate.",
    syntax: "Complete the 30 exam questions covering all topics.",
    database: "company",
    tables: ["employees", "departments"],
    challenge: "Find the department name and the maximum salary in that department, but only show departments whose maximum salary is greater than 100000.",
    hint: "Join employees and departments, group by department_name, and filter with HAVING MAX(salary) > 100000.",
    solution: "SELECT d.department_name, MAX(e.salary) AS max_salary FROM departments d INNER JOIN employees e ON d.department_id = e.department_id GROUP BY d.department_name HAVING MAX(e.salary) > 100000",
    requiredKeywords: ["select", "department_name", "max(salary)", "join", "group", "by", "having", "100000"]
  }
];

// Expose to global/window scope
if (typeof window !== 'undefined') {
  window.LEVELS = LEVELS;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { LEVELS };
}
